### ISSUE TITLE
Lighten/Darken missing

### ISSUE THREAD

**Issue by esso23** [chanan/Polished.net#1]
Hi,
I can't find lighten/darken functions. Found them in polished.js docs:
https://polished.js.org/docs/#lighten
https://polished.js.org/docs/#darken

**Comment by chanan** [comment]
Hi @esso23 

I think you are looking for:
https://github.com/chanan/Polished.net/blob/master/src/Polished.net.tests/Types/Lighten.cs
https://github.com/chanan/Polished.net/blob/master/src/Polished.net.tests/Types/Darken.cs

**Comment by esso23** [comment]
Oh, I didn't realize it's only available on HslColor. My bad.
Thanks for a quick response and also for great libraries (enjoying BlazorStyled aswell).

**Comment by chanan** [comment]
@esso23 You can easily convert between HSL Color and the other colors - so you should be able to work in any color format you want. Glad its getting some use!
